"""The hot-function linker fragment (docs/vm/r5-icache.md) from a list of names.

    python tools/r5sim/icache.py model ... --pack-kib 8 --emit hot.txt
    python tools/r5sim/gen_hot_lf.py hot.txt build_x/cardputer_pocketjs.map > main/r5_hot.lf

Each name becomes a mapping entry to flash_text with an ALIGN flag. The flag
is the point, not the alignment: a function mapped to where it already goes
("(default)" alone) is dropped by ldgen as no change, while a flagged one gets
its own input-section rule after .flash.text's catch-all -- so every listed
function lands in one run at the end of the generic code instead of wherever
its archive and object put it. Where each one lives (archive, object) comes
from the map of a build that has not moved it yet.
"""
import collections, re, sys

# --noflash: the same list into IRAM instead (costs its size in DRAM).
noflash = '--noflash' in sys.argv
if noflash:
    sys.argv.remove('--noflash')
names = [n.strip() for n in open(sys.argv[1]) if n.strip()]
want = set(names)
where = {}
text = open(sys.argv[2], encoding='utf-8', errors='replace').read()
# " .text.NAME\n                0xADDR 0xSIZE path/libX.a(obj.c.obj)"
for m in re.finditer(r'^ \.text\.(\S+)\s*\n?\s+0x[0-9a-f]+\s+0x[0-9a-f]+ (.*?([^/\\]+\.a)\(([^)]+)\))\s*$',
                     text, re.M):
    name, archive, obj = m.group(1), m.group(3), m.group(4)
    if name in want and name not in where:
        where[name] = (archive, obj.split('.')[0])
by_archive = collections.OrderedDict()
skipped = []
for n in names:
    if n not in where or '$' in n:
        skipped.append(n); continue
    ar, ob = where[n]
    by_archive.setdefault(ar, []).append((ob, n))
print('# Generated by tools/r5sim/gen_hot_lf.py -- see docs/vm/r5-icache.md.')
if noflash:
    print('# The functions a STRESS turn fetches most per byte, in IRAM: fetched')
    print('# without the instruction cache, at their size in DRAM.')
else:
    print('# The functions a STRESS turn fetches most per byte, in one run at the end')
    print('# of .flash.text, so that they stop competing with each other for the')
    print('# instruction cache\'s sets.')
print('# Regenerate from a fresh model; do not hand-edit.')
for i, (ar, entries) in enumerate(by_archive.items()):
    print(f'\n[mapping:r5_{"iram" if noflash else "hot"}_{i}]\narchive: {ar}\nentries:')
    for ob, n in entries:
        if noflash:
            print(f'    {ob}: {n} (noflash)')
        else:
            print(f'    {ob}: {n} (default);\n        text->flash_text ALIGN(4, pre)')
if skipped:
    print(f'# not placed ({len(skipped)}): ' + ' '.join(skipped), file=sys.stderr)
