// F1 (docs/vm/builtin-floor-plan.md sec.5.1): generate the flash-resident
// atom table, components/quickjs-ng/quickjs-ng/quickjs-rom-atoms.h.
//
// Built against the engine WITHOUT CONFIG_POCKET_VM_ROM_ATOMS: the table has
// to describe what today's JS_NewContext creates, and it is compiled with
// quickjs.c included so the heap can be read from inside.
//
// What goes in:
//   - every predefined string atom (index < JS_ATOM_END) except the empty
//     string, which js_empty_string() hands out as a value on hot paths and
//     so stays a heap JSString;
//   - every string atom JS_NewContext creates beyond the predefined list
//     (method names, "get length", ...), numbered JS_ATOM_END.. in name
//     order so the output does not depend on creation order.
// Symbols, the private brand and atom 0 stay on the heap.
//
// Checked while generating, because the runtime relies on each:
//   - the hash baked here equals the hash the runtime computed for the atom;
//   - no ROM name is an array index (those become tagged ints, never atoms);
//   - every ROM name is 8-bit (the lookup compares 16-bit strings against
//     8-bit ROM text by code unit).
#include "quickjs.c"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char *s; uint32_t len, hash; uint32_t old_index; bool numeric; } ent_t;

static int by_name(const void *a, const void *b) {
    const ent_t *x = a, *y = b;
    uint32_t n = x->len < y->len ? x->len : y->len;
    int c = memcmp(x->s, y->s, n);
    return c ? c : (int)x->len - (int)y->len;
}

static void put_c_string(FILE *f, const char *s, uint32_t len) {
    fputc('"', f);
    for (uint32_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '"' || c == '\\') fprintf(f, "\\%c", c);
        else if (c < 32 || c >= 127) fprintf(f, "\\%03o", c);
        else fputc(c, f);
    }
    fputc('"', f);
}

int main(int argc, char **argv) {
    if (argc != 2) { fprintf(stderr, "usage: %s OUT.h\n", argv[0]); return 2; }
    JSRuntime *rt = JS_NewRuntime();
    JSContext *ctx = JS_NewContext(rt);

    static ent_t pre[JS_ATOM_END], extra[4096];
    unsigned n_extra = 0;
    bool is_rom[JS_ATOM_END] = {0};
    for (int i = 1; i < rt->atom_size; i++) {
        JSAtomStruct *p = rt->atom_array[i];
        if (atom_is_free(p) || p->atom_type != JS_ATOM_TYPE_STRING) continue;
        if (i == JS_ATOM_empty_string) continue;
        if (p->is_wide_char) { fprintf(stderr, "atom %d is wide\n", i); return 1; }
        uint32_t v;
        if (is_num_string(&v, p)) { fprintf(stderr, "atom %d is an index\n", i); return 1; }
        uint32_t h = hash_string8(str8(p), p->len, JS_ATOM_TYPE_STRING) & JS_ATOM_HASH_MASK;
        if (h != p->hash) { fprintf(stderr, "atom %d hash mismatch\n", i); return 1; }
        int num = JS_AtomIsNumericIndex(ctx, i);
        if (num < 0) { fprintf(stderr, "atom %d numeric check threw\n", i); return 1; }
        ent_t e = {(const char *)str8(p), p->len, h, (uint32_t)i, num == 1};
        if (i < JS_ATOM_END) { pre[i] = e; is_rom[i] = true; }
        else {
            if (n_extra == sizeof extra / sizeof extra[0]) { fprintf(stderr, "too many\n"); return 1; }
            extra[n_extra++] = e;
        }
    }
    // ROM_NO_EXTRAS=1: leave the context-created names out, i.e. a table
    // that is stale in the one way that is allowed -- the negative control
    // N1a (tools/vmtest/floor/f1_faults.sh) builds with it and must still
    // pass, those names becoming ordinary heap atoms.
    if (getenv("ROM_NO_EXTRAS"))
        n_extra = 0;
    qsort(extra, n_extra, sizeof extra[0], by_name);
    uint32_t end = JS_ATOM_END + n_extra;
    if (end > 0xffff) { fprintf(stderr, "table index overflows uint16\n"); return 1; }

    // Record per atom index [0, end); the blob holds each name followed by a
    // NUL so a record's text can be handed to C string code as it is.
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror(argv[1]); return 1; }
    uint32_t n_rom = 0, blob = 0;
    fprintf(f, "/* Generated by tools/vmtest/floor/gen_rom_atoms.sh from this tree's\n"
               " * JS_NewContext -- do not edit. docs/vm/builtin-floor-plan.md sec.5.1.\n"
               " * Regenerate after any change to the builtins; a stale table is still\n"
               " * correct (a missing name becomes an ordinary heap atom) but saves less. */\n\n");
    fprintf(f, "static const char js_rom_chars[] =\n");
    uint32_t *off = calloc(end, sizeof *off);
    for (uint32_t i = 1; i < end; i++) {
        const ent_t *e = i < JS_ATOM_END ? (is_rom[i] ? &pre[i] : NULL) : &extra[i - JS_ATOM_END];
        if (!e) continue;
        off[i] = blob;
        fprintf(f, "    ");
        put_c_string(f, e->s, e->len);
        fprintf(f, " \"\\0\"\n");
        blob += e->len + 1;
        n_rom++;
    }
    fprintf(f, "    ;\n\n");
    if (blob > 0xffff) { fprintf(stderr, "blob offset overflows uint16\n"); return 1; }

    fprintf(f, "static const JSRomAtom js_rom_atoms[JS_ROM_ATOM_END] = {\n");
    for (uint32_t i = 0; i < end; i++) {
        const ent_t *e = i == 0 ? NULL : i < JS_ATOM_END ? (is_rom[i] ? &pre[i] : NULL)
                                                        : &extra[i - JS_ATOM_END];
        if (!e) { fprintf(f, "    {0, JS_ROM_NOT, 0},\n"); continue; }
        fprintf(f, "    {0x%07xu%s, %u, %u}, /* %u ", e->hash, e->numeric ? " | JS_ROM_NUMERIC" : "",
                e->len, off[i], i);
        for (uint32_t k = 0; k < e->len && k < 40; k++)
            fputc(e->s[k] == '*' ? '.' : e->s[k], f);
        fprintf(f, " */\n");
    }
    fprintf(f, "};\n\n");

    // Open addressing on the runtime's own hash, load <= 1/2.
    uint32_t bits = 1;
    while ((1u << bits) < n_rom * 2) bits++;
    uint32_t size = 1u << bits;
    uint16_t *tab = calloc(size, sizeof *tab);
    uint32_t probes_max = 0, probes_sum = 0;
    for (uint32_t i = 1; i < end; i++) {
        const ent_t *e = i < JS_ATOM_END ? (is_rom[i] ? &pre[i] : NULL) : &extra[i - JS_ATOM_END];
        if (!e) continue;
        uint32_t j = e->hash & (size - 1), probes = 1;
        while (tab[j]) { j = (j + 1) & (size - 1); probes++; }
        tab[j] = (uint16_t)i;
        probes_sum += probes;
        if (probes > probes_max) probes_max = probes;
    }
    fprintf(f, "static const uint16_t js_rom_hash[1u << JS_ROM_HASH_BITS] = {");
    for (uint32_t j = 0; j < size; j++)
        fprintf(f, "%s%u,", j % 16 ? "" : "\n    ", tab[j]);
    fprintf(f, "\n};\n");
    fclose(f);

    // The header's parameters go in a second, tiny file included first, so
    // quickjs.c can size its arrays before the tables themselves.
    char path[4096];
    snprintf(path, sizeof path, "%s", argv[1]);
    char *dot = strrchr(path, '.');
    if (!dot) return 1;
    strcpy(dot, "-defs.h");
    f = fopen(path, "w");
    if (!f) { perror(path); return 1; }
    fprintf(f, "/* Generated with quickjs-rom-atoms.h -- do not edit. */\n"
               "#define JS_ROM_ATOM_END %uu   /* first atom number past the table */\n"
               "#define JS_ROM_ATOM_COUNT %uu /* names in flash */\n"
               "#define JS_ROM_HASH_BITS %uu\n"
               "#define JS_ROM_PREDEF_END %uu /* JS_ATOM_END when generated */\n",
               end, n_rom, bits, (unsigned)JS_ATOM_END);
    fclose(f);

    printf("rom names=%u (predefined %u, extra %u) end=%u blob=%u B records=%u B hash=%u B"
           " probes max=%u mean=%.2f\n",
           n_rom, n_rom - n_extra, n_extra, end, blob, end * 8, size * 2,
           probes_max, (double)probes_sum / n_rom);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 0;
}
