/* Generated by tools/vmtest/floor/gen_rom_atoms.sh from this tree's
 * JS_NewContext -- do not edit. docs/vm/builtin-floor-plan.md sec.5.1.
 * Regenerate after any change to the builtins; a stale table is still
 * correct (a missing name becomes an ordinary heap atom) but saves less. */

static const char js_rom_chars[] =
    "null" "\0"
    "false" "\0"
    "true" "\0"
    "if" "\0"
    "else" "\0"
    "return" "\0"
    "var" "\0"
    "this" "\0"
    "delete" "\0"
    "void" "\0"
    "typeof" "\0"
    "new" "\0"
    "in" "\0"
    "instanceof" "\0"
    "do" "\0"
    "while" "\0"
    "for" "\0"
    "break" "\0"
    "continue" "\0"
    "switch" "\0"
    "case" "\0"
    "default" "\0"
    "throw" "\0"
    "try" "\0"
    "catch" "\0"
    "finally" "\0"
    "function" "\0"
    "debugger" "\0"
    "with" "\0"
    "class" "\0"
    "const" "\0"
    "enum" "\0"
    "export" "\0"
    "extends" "\0"
    "import" "\0"
    "super" "\0"
    "implements" "\0"
    "interface" "\0"
    "let" "\0"
    "package" "\0"
    "private" "\0"
    "protected" "\0"
    "public" "\0"
    "static" "\0"
    "yield" "\0"
    "await" "\0"
    "keys" "\0"
    "size" "\0"
    "length" "\0"
    "message" "\0"
    "cause" "\0"
    "errors" "\0"
    "stack" "\0"
    "name" "\0"
    "toString" "\0"
    "toLocaleString" "\0"
    "valueOf" "\0"
    "eval" "\0"
    "prototype" "\0"
    "constructor" "\0"
    "configurable" "\0"
    "writable" "\0"
    "enumerable" "\0"
    "value" "\0"
    "get" "\0"
    "set" "\0"
    "of" "\0"
    "__proto__" "\0"
    "undefined" "\0"
    "number" "\0"
    "boolean" "\0"
    "string" "\0"
    "object" "\0"
    "symbol" "\0"
    "integer" "\0"
    "unknown" "\0"
    "arguments" "\0"
    "callee" "\0"
    "caller" "\0"
    "<eval>" "\0"
    "<ret>" "\0"
    "<var>" "\0"
    "<arg_var>" "\0"
    "<with>" "\0"
    "lastIndex" "\0"
    "target" "\0"
    "index" "\0"
    "input" "\0"
    "defineProperties" "\0"
    "apply" "\0"
    "join" "\0"
    "concat" "\0"
    "split" "\0"
    "construct" "\0"
    "getPrototypeOf" "\0"
    "setPrototypeOf" "\0"
    "isExtensible" "\0"
    "preventExtensions" "\0"
    "has" "\0"
    "deleteProperty" "\0"
    "defineProperty" "\0"
    "getOwnPropertyDescriptor" "\0"
    "ownKeys" "\0"
    "add" "\0"
    "done" "\0"
    "next" "\0"
    "values" "\0"
    "source" "\0"
    "flags" "\0"
    "global" "\0"
    "unicode" "\0"
    "raw" "\0"
    "rawJSON" "\0"
    "new.target" "\0"
    "this.active_func" "\0"
    "<home_object>" "\0"
    "<computed_field>" "\0"
    "<static_computed_field>" "\0"
    "<class_fields_init>" "\0"
    "<brand>" "\0"
    "#constructor" "\0"
    "as" "\0"
    "from" "\0"
    "fromAsync" "\0"
    "meta" "\0"
    "*default*" "\0"
    "*" "\0"
    "Module" "\0"
    "then" "\0"
    "resolve" "\0"
    "reject" "\0"
    "promise" "\0"
    "proxy" "\0"
    "revoke" "\0"
    "async" "\0"
    "exec" "\0"
    "groups" "\0"
    "indices" "\0"
    "status" "\0"
    "reason" "\0"
    "globalThis" "\0"
    "bigint" "\0"
    "not-equal" "\0"
    "timed-out" "\0"
    "ok" "\0"
    "toJSON" "\0"
    "maxByteLength" "\0"
    "zip" "\0"
    "zipKeyed" "\0"
    "Object" "\0"
    "Array" "\0"
    "Error" "\0"
    "Number" "\0"
    "String" "\0"
    "Boolean" "\0"
    "Symbol" "\0"
    "Arguments" "\0"
    "Math" "\0"
    "JSON" "\0"
    "Date" "\0"
    "Function" "\0"
    "GeneratorFunction" "\0"
    "ForInIterator" "\0"
    "RegExp" "\0"
    "ArrayBuffer" "\0"
    "SharedArrayBuffer" "\0"
    "Uint8ClampedArray" "\0"
    "Int8Array" "\0"
    "Uint8Array" "\0"
    "Int16Array" "\0"
    "Uint16Array" "\0"
    "Int32Array" "\0"
    "Uint32Array" "\0"
    "BigInt64Array" "\0"
    "BigUint64Array" "\0"
    "Float16Array" "\0"
    "Float32Array" "\0"
    "Float64Array" "\0"
    "DataView" "\0"
    "BigInt" "\0"
    "WeakRef" "\0"
    "FinalizationRegistry" "\0"
    "Map" "\0"
    "Set" "\0"
    "WeakMap" "\0"
    "WeakSet" "\0"
    "Iterator" "\0"
    "Iterator Concat" "\0"
    "Iterator Helper" "\0"
    "Iterator Wrap" "\0"
    "Map Iterator" "\0"
    "Set Iterator" "\0"
    "Array Iterator" "\0"
    "String Iterator" "\0"
    "RegExp String Iterator" "\0"
    "Generator" "\0"
    "Proxy" "\0"
    "Promise" "\0"
    "PromiseResolveFunction" "\0"
    "PromiseRejectFunction" "\0"
    "AsyncFunction" "\0"
    "AsyncFunctionResolve" "\0"
    "AsyncFunctionReject" "\0"
    "AsyncGeneratorFunction" "\0"
    "AsyncGenerator" "\0"
    "EvalError" "\0"
    "RangeError" "\0"
    "ReferenceError" "\0"
    "SyntaxError" "\0"
    "TypeError" "\0"
    "URIError" "\0"
    "InternalError" "\0"
    "DOMException" "\0"
    "CallSite" "\0"
    "ABORT_ERR" "\0"
    "AggregateError" "\0"
    "Atomics" "\0"
    "BYTES_PER_ELEMENT" "\0"
    "DATA_CLONE_ERR" "\0"
    "DOMSTRING_SIZE_ERR" "\0"
    "EPSILON" "\0"
    "HIERARCHY_REQUEST_ERR" "\0"
    "INDEX_SIZE_ERR" "\0"
    "INUSE_ATTRIBUTE_ERR" "\0"
    "INVALID_ACCESS_ERR" "\0"
    "INVALID_CHARACTER_ERR" "\0"
    "INVALID_MODIFICATION_ERR" "\0"
    "INVALID_NODE_TYPE_ERR" "\0"
    "INVALID_STATE_ERR" "\0"
    "Infinity" "\0"
    "MAX_SAFE_INTEGER" "\0"
    "MAX_VALUE" "\0"
    "MIN_SAFE_INTEGER" "\0"
    "MIN_VALUE" "\0"
    "NAMESPACE_ERR" "\0"
    "NEGATIVE_INFINITY" "\0"
    "NETWORK_ERR" "\0"
    "NOT_FOUND_ERR" "\0"
    "NOT_SUPPORTED_ERR" "\0"
    "NO_DATA_ALLOWED_ERR" "\0"
    "NO_MODIFICATION_ALLOWED_ERR" "\0"
    "NaN" "\0"
    "POSITIVE_INFINITY" "\0"
    "QUOTA_EXCEEDED_ERR" "\0"
    "Reflect" "\0"
    "SECURITY_ERR" "\0"
    "SYNTAX_ERR" "\0"
    "TIMEOUT_ERR" "\0"
    "TYPE_MISMATCH_ERR" "\0"
    "TypedArray" "\0"
    "URL_MISMATCH_ERR" "\0"
    "UTC" "\0"
    "VALIDATION_ERR" "\0"
    "WRONG_DOCUMENT_ERR" "\0"
    "__defineGetter__" "\0"
    "__defineSetter__" "\0"
    "__lookupGetter__" "\0"
    "__lookupSetter__" "\0"
    "all" "\0"
    "allSettled" "\0"
    "anchor" "\0"
    "any" "\0"
    "asIntN" "\0"
    "asUintN" "\0"
    "assign" "\0"
    "asyncIterator" "\0"
    "at" "\0"
    "big" "\0"
    "bind" "\0"
    "blink" "\0"
    "bold" "\0"
    "buffer" "\0"
    "byteLength" "\0"
    "byteOffset" "\0"
    "call" "\0"
    "captureStackTrace" "\0"
    "charAt" "\0"
    "charCodeAt" "\0"
    "clear" "\0"
    "code" "\0"
    "codePointAt" "\0"
    "columnNumber" "\0"
    "compile" "\0"
    "copyWithin" "\0"
    "create" "\0"
    "decodeURI" "\0"
    "decodeURIComponent" "\0"
    "deref" "\0"
    "description" "\0"
    "detached" "\0"
    "difference" "\0"
    "dotAll" "\0"
    "drop" "\0"
    "encodeURI" "\0"
    "encodeURIComponent" "\0"
    "endsWith" "\0"
    "entries" "\0"
    "escape" "\0"
    "every" "\0"
    "fileName" "\0"
    "fill" "\0"
    "filter" "\0"
    "find" "\0"
    "findIndex" "\0"
    "findLast" "\0"
    "findLastIndex" "\0"
    "fixed" "\0"
    "flat" "\0"
    "flatMap" "\0"
    "fontcolor" "\0"
    "fontsize" "\0"
    "forEach" "\0"
    "freeze" "\0"
    "fromCharCode" "\0"
    "fromCodePoint" "\0"
    "fromEntries" "\0"
    "get [Symbol.species]" "\0"
    "get [Symbol.toStringTag]" "\0"
    "get __proto__" "\0"
    "get buffer" "\0"
    "get byteLength" "\0"
    "get byteOffset" "\0"
    "get code" "\0"
    "get columnNumber" "\0"
    "get description" "\0"
    "get detached" "\0"
    "get dotAll" "\0"
    "get fileName" "\0"
    "get flags" "\0"
    "get global" "\0"
    "get growable" "\0"
    "get hasIndices" "\0"
    "get ignoreCase" "\0"
    "get immutable" "\0"
    "get length" "\0"
    "get lineNumber" "\0"
    "get maxByteLength" "\0"
    "get message" "\0"
    "get multiline" "\0"
    "get name" "\0"
    "get prepareStackTrace" "\0"
    "get resizable" "\0"
    "get size" "\0"
    "get source" "\0"
    "get stackTraceLimit" "\0"
    "get sticky" "\0"
    "get unicode" "\0"
    "get unicodeSets" "\0"
    "getBigInt64" "\0"
    "getBigUint64" "\0"
    "getColumnNumber" "\0"
    "getDate" "\0"
    "getDay" "\0"
    "getFileName" "\0"
    "getFloat16" "\0"
    "getFloat32" "\0"
    "getFloat64" "\0"
    "getFullYear" "\0"
    "getFunction" "\0"
    "getFunctionName" "\0"
    "getHours" "\0"
    "getInt16" "\0"
    "getInt32" "\0"
    "getInt8" "\0"
    "getLineNumber" "\0"
    "getMilliseconds" "\0"
    "getMinutes" "\0"
    "getMonth" "\0"
    "getOrInsert" "\0"
    "getOrInsertComputed" "\0"
    "getOwnPropertyDescriptors" "\0"
    "getOwnPropertyNames" "\0"
    "getOwnPropertySymbols" "\0"
    "getSeconds" "\0"
    "getTime" "\0"
    "getTimezoneOffset" "\0"
    "getUTCDate" "\0"
    "getUTCDay" "\0"
    "getUTCFullYear" "\0"
    "getUTCHours" "\0"
    "getUTCMilliseconds" "\0"
    "getUTCMinutes" "\0"
    "getUTCMonth" "\0"
    "getUTCSeconds" "\0"
    "getUint16" "\0"
    "getUint32" "\0"
    "getUint8" "\0"
    "getYear" "\0"
    "groupBy" "\0"
    "grow" "\0"
    "growable" "\0"
    "hasIndices" "\0"
    "hasInstance" "\0"
    "hasOwn" "\0"
    "hasOwnProperty" "\0"
    "ignoreCase" "\0"
    "immutable" "\0"
    "includes" "\0"
    "indexOf" "\0"
    "intersection" "\0"
    "is" "\0"
    "isArray" "\0"
    "isConcatSpreadable" "\0"
    "isDisjointFrom" "\0"
    "isError" "\0"
    "isFinite" "\0"
    "isFrozen" "\0"
    "isInteger" "\0"
    "isNaN" "\0"
    "isNative" "\0"
    "isPrototypeOf" "\0"
    "isSafeInteger" "\0"
    "isSealed" "\0"
    "isSubsetOf" "\0"
    "isSupersetOf" "\0"
    "isView" "\0"
    "isWellFormed" "\0"
    "italics" "\0"
    "iterator" "\0"
    "keyFor" "\0"
    "lastIndexOf" "\0"
    "lineNumber" "\0"
    "link" "\0"
    "localeCompare" "\0"
    "map" "\0"
    "match" "\0"
    "matchAll" "\0"
    "multiline" "\0"
    "normalize" "\0"
    "now" "\0"
    "padEnd" "\0"
    "padStart" "\0"
    "parse" "\0"
    "parseFloat" "\0"
    "parseInt" "\0"
    "performance" "\0"
    "pop" "\0"
    "prepareStackTrace" "\0"
    "propertyIsEnumerable" "\0"
    "push" "\0"
    "queueMicrotask" "\0"
    "race" "\0"
    "reduce" "\0"
    "reduceRight" "\0"
    "register" "\0"
    "repeat" "\0"
    "replace" "\0"
    "replaceAll" "\0"
    "resizable" "\0"
    "resize" "\0"
    "reverse" "\0"
    "revocable" "\0"
    "seal" "\0"
    "search" "\0"
    "set [Symbol.toStringTag]" "\0"
    "set __proto__" "\0"
    "set prepareStackTrace" "\0"
    "set stackTraceLimit" "\0"
    "setBigInt64" "\0"
    "setBigUint64" "\0"
    "setDate" "\0"
    "setFloat16" "\0"
    "setFloat32" "\0"
    "setFloat64" "\0"
    "setFullYear" "\0"
    "setHours" "\0"
    "setInt16" "\0"
    "setInt32" "\0"
    "setInt8" "\0"
    "setMilliseconds" "\0"
    "setMinutes" "\0"
    "setMonth" "\0"
    "setSeconds" "\0"
    "setTime" "\0"
    "setUTCDate" "\0"
    "setUTCFullYear" "\0"
    "setUTCHours" "\0"
    "setUTCMilliseconds" "\0"
    "setUTCMinutes" "\0"
    "setUTCMonth" "\0"
    "setUTCSeconds" "\0"
    "setUint16" "\0"
    "setUint32" "\0"
    "setUint8" "\0"
    "setYear" "\0"
    "shift" "\0"
    "slice" "\0"
    "sliceToImmutable" "\0"
    "small" "\0"
    "some" "\0"
    "sort" "\0"
    "species" "\0"
    "splice" "\0"
    "stackTraceLimit" "\0"
    "startsWith" "\0"
    "sticky" "\0"
    "strike" "\0"
    "sub" "\0"
    "subarray" "\0"
    "substr" "\0"
    "substring" "\0"
    "sup" "\0"
    "symmetricDifference" "\0"
    "take" "\0"
    "test" "\0"
    "timeOrigin" "\0"
    "toArray" "\0"
    "toDateString" "\0"
    "toExponential" "\0"
    "toFixed" "\0"
    "toGMTString" "\0"
    "toISOString" "\0"
    "toLocaleDateString" "\0"
    "toLocaleLowerCase" "\0"
    "toLocaleTimeString" "\0"
    "toLocaleUpperCase" "\0"
    "toLowerCase" "\0"
    "toPrecision" "\0"
    "toPrimitive" "\0"
    "toReversed" "\0"
    "toSorted" "\0"
    "toSpliced" "\0"
    "toStringTag" "\0"
    "toTimeString" "\0"
    "toUTCString" "\0"
    "toUpperCase" "\0"
    "toWellFormed" "\0"
    "transfer" "\0"
    "transferToFixedLength" "\0"
    "transferToImmutable" "\0"
    "trim" "\0"
    "trimEnd" "\0"
    "trimLeft" "\0"
    "trimRight" "\0"
    "trimStart" "\0"
    "unescape" "\0"
    "unicodeSets" "\0"
    "union" "\0"
    "unregister" "\0"
    "unscopables" "\0"
    "unshift" "\0"
    "withResolvers" "\0"
    ;

static const JSRomAtom js_rom_atoms[JS_ROM_ATOM_END] = {
    {0, JS_ROM_NOT, 0},
    {0x4ed0e88u, 4, 0}, /* 1 null */
    {0x07f337au, 5, 5}, /* 2 false */
    {0xb6b6737u, 4, 11}, /* 3 true */
    {0x0017a76u, 2, 16}, /* 4 if */
    {0xb215eeau, 4, 19}, /* 5 else */
    {0xb081491u, 6, 24}, /* 6 return */
    {0x1928306u, 3, 31}, /* 7 var */
    {0xb60cd07u, 4, 35}, /* 8 this */
    {0x82273acu, 6, 40}, /* 9 delete */
    {0xd9358fdu, 4, 47}, /* 10 void */
    {0xd2f15eau, 6, 52}, /* 11 typeof */
    {0x18a159fu, 3, 59}, /* 12 new */
    {0x0017a7eu, 2, 63}, /* 13 in */
    {0xd1cf505u, 10, 66}, /* 14 instanceof */
    {0x001755cu, 2, 77}, /* 15 do */
    {0x7f4cb88u, 5, 80}, /* 16 while */
    {0x181ae58u, 3, 86}, /* 17 for */
    {0xe3901eeu, 5, 90}, /* 18 break */
    {0x163f230u, 8, 96}, /* 19 continue */
    {0x3bbdeadu, 6, 105}, /* 20 switch */
    {0x8ea9a21u, 4, 112}, /* 21 case */
    {0x80b39e8u, 7, 117}, /* 22 default */
    {0x07c1e45u, 5, 125}, /* 23 throw */
    {0x1907822u, 3, 131}, /* 24 try */
    {0x9056472u, 5, 135}, /* 25 catch */
    {0x426eafau, 7, 141}, /* 26 finally */
    {0x1bc22b1u, 8, 149}, /* 27 function */
    {0xd645ba2u, 8, 158}, /* 28 debugger */
    {0xea2a37fu, 4, 167}, /* 29 with */
    {0x4dec707u, 5, 172}, /* 30 class */
    {0x82d3c8au, 5, 178}, /* 31 const */
    {0xb237d62u, 4, 184}, /* 32 enum */
    {0xe50fdcdu, 6, 189}, /* 33 export */
    {0xf063ef8u, 7, 196}, /* 34 extends */
    {0xbc83d3eu, 6, 204}, /* 35 import */
    {0x1671aa2u, 5, 211}, /* 36 super */
    {0x6f7e4a9u, 10, 217}, /* 37 implements */
    {0x92b2db0u, 9, 228}, /* 38 interface */
    {0x187f93au, 3, 238}, /* 39 let */
    {0x7b79c55u, 7, 242}, /* 40 package */
    {0x390facau, 7, 250}, /* 41 private */
    {0x7c5f985u, 9, 258}, /* 42 protected */
    {0xb062632u, 6, 268}, /* 43 public */
    {0x38d11f7u, 6, 275}, /* 44 static */
    {0x35cf1dcu, 5, 282}, /* 45 yield */
    {0x67551bdu, 5, 288}, /* 46 await */
    {0, JS_ROM_NOT, 0},
    {0x19b7bd5u, 4, 294}, /* 48 keys */
    {0xa4c584au, 4, 299}, /* 49 size */
    {0x6f8edf7u, 6, 304}, /* 50 length */
    {0x2bf0f06u, 7, 311}, /* 51 message */
    {0x9068310u, 5, 319}, /* 52 cause */
    {0x177c634u, 6, 325}, /* 53 errors */
    {0x041af57u, 5, 332}, /* 54 stack */
    {0x4d7f3b4u, 4, 338}, /* 55 name */
    {0x5becee5u, 8, 343}, /* 56 toString */
    {0x4732bf7u, 14, 352}, /* 57 toLocaleString */
    {0x67a59a7u, 7, 367}, /* 58 valueOf */
    {0xb2bda5du, 4, 375}, /* 59 eval */
    {0xdec1b59u, 9, 380}, /* 60 prototype */
    {0x9c4a631u, 11, 390}, /* 61 constructor */
    {0x66667aau, 12, 402}, /* 62 configurable */
    {0xfbb9aa9u, 8, 415}, /* 63 writable */
    {0x7b4c6a9u, 10, 424}, /* 64 enumerable */
    {0x3358b98u, 5, 435}, /* 65 value */
    {0x182b245u, 3, 441}, /* 66 get */
    {0x18f5c91u, 3, 445}, /* 67 set */
    {0x00180a0u, 2, 449}, /* 68 of */
    {0x081320fu, 9, 452}, /* 69 __proto__ */
    {0x391bcafu, 9, 462}, /* 70 undefined */
    {0x7bea6aau, 6, 472}, /* 71 number */
    {0x1cc530fu, 7, 479}, /* 72 boolean */
    {0x5f054cau, 6, 487}, /* 73 string */
    {0x1ddb2a0u, 6, 494}, /* 74 object */
    {0x25607b1u, 6, 501}, /* 75 symbol */
    {0xc163065u, 7, 508}, /* 76 integer */
    {0xa1addd9u, 7, 516}, /* 77 unknown */
    {0xe06445du, 9, 524}, /* 78 arguments */
    {0xbe70b6fu, 6, 534}, /* 79 callee */
    {0xbe70b7cu, 6, 541}, /* 80 caller */
    {0x3a7f3d7u, 6, 548}, /* 81 <eval> */
    {0x9c808e0u, 5, 555}, /* 82 <ret> */
    {0xe1a1f6au, 5, 561}, /* 83 <var> */
    {0xbec3ee3u, 9, 567}, /* 84 <arg_var> */
    {0x2b095c5u, 6, 577}, /* 85 <with> */
    {0x1867383u, 9, 584}, /* 86 lastIndex */
    {0x34acfaau, 6, 594}, /* 87 target */
    {0x6116c31u, 5, 601}, /* 88 index */
    {0x61e26e9u, 5, 607}, /* 89 input */
    {0xb4946f7u, 16, 613}, /* 90 defineProperties */
    {0xeee1b55u, 5, 630}, /* 91 apply */
    {0x09064f3u, 4, 636}, /* 92 join */
    {0x6683ba5u, 6, 641}, /* 93 concat */
    {0xbf70049u, 5, 648}, /* 94 split */
    {0xb4c5396u, 9, 654}, /* 95 construct */
    {0x5300f94u, 14, 664}, /* 96 getPrototypeOf */
    {0x1a7d668u, 14, 679}, /* 97 setPrototypeOf */
    {0xec5152eu, 12, 694}, /* 98 isExtensible */
    {0x2c48273u, 17, 707}, /* 99 preventExtensions */
    {0x183bc59u, 3, 725}, /* 100 has */
    {0xd2fe111u, 14, 729}, /* 101 deleteProperty */
    {0x35ee5a1u, 14, 744}, /* 102 defineProperty */
    {0x56a19f5u, 24, 759}, /* 103 getOwnPropertyDescriptor */
    {0x27d54b9u, 7, 784}, /* 104 ownKeys */
    {0x17c5c08u, 3, 792}, /* 105 add */
    {0xa0ef003u, 4, 796}, /* 106 done */
    {0x4dc37d4u, 4, 801}, /* 107 next */
    {0xc02699bu, 6, 806}, /* 108 values */
    {0x7618b54u, 6, 813}, /* 109 source */
    {0xc60ead6u, 5, 820}, /* 110 flags */
    {0xe4f2c3cu, 6, 826}, /* 111 global */
    {0x3d69fccu, 7, 833}, /* 112 unicode */
    {0x18e4a47u, 3, 841}, /* 113 raw */
    {0xfb9f467u, 7, 845}, /* 114 rawJSON */
    {0xcee6f90u, 10, 853}, /* 115 new.target */
    {0x8af09beu, 16, 864}, /* 116 this.active_func */
    {0xe95a32au, 13, 881}, /* 117 <home_object> */
    {0x38f9c0bu, 16, 895}, /* 118 <computed_field> */
    {0x7de42e8u, 23, 912}, /* 119 <static_computed_field> */
    {0xd5715eau, 19, 936}, /* 120 <class_fields_init> */
    {0x620bc12u, 7, 956}, /* 121 <brand> */
    {0x827e460u, 12, 964}, /* 122 #constructor */
    {0x001724bu, 2, 977}, /* 123 as */
    {0xc3d4453u, 4, 980}, /* 124 from */
    {0x2a16b69u, 9, 985}, /* 125 fromAsync */
    {0x3c69f4eu, 4, 995}, /* 126 meta */
    {0x26802b2u, 9, 1000}, /* 127 .default. */
    {0x0000131u, 1, 1010}, /* 128 . */
    {0x4d22895u, 6, 1012}, /* 129 Module */
    {0xb60c8e6u, 4, 1019}, /* 130 then */
    {0x199f503u, 7, 1024}, /* 131 resolve */
    {0x01f56b8u, 6, 1032}, /* 132 reject */
    {0x8db9482u, 7, 1039}, /* 133 promise */
    {0x6a332d5u, 5, 1047}, /* 134 proxy */
    {0xd2ce0dfu, 6, 1053}, /* 135 revoke */
    {0x2385a0bu, 5, 1060}, /* 136 async */
    {0xb2dfad2u, 4, 1066}, /* 137 exec */
    {0xd67a995u, 6, 1071}, /* 138 groups */
    {0xdb1f2eeu, 7, 1078}, /* 139 indices */
    {0x38d1e5bu, 6, 1086}, /* 140 status */
    {0x66bf2a5u, 6, 1093}, /* 141 reason */
    {0xe0a4b82u, 10, 1100}, /* 142 globalThis */
    {0x83e08d8u, 6, 1111}, /* 143 bigint */
    {0x753fe81u, 9, 1118}, /* 144 not-equal */
    {0x7ef57bfu, 9, 1128}, /* 145 timed-out */
    {0x00180a5u, 2, 1138}, /* 146 ok */
    {0x035faccu, 6, 1141}, /* 147 toJSON */
    {0x9a97e51u, 13, 1148}, /* 148 maxByteLength */
    {0x196c400u, 3, 1162}, /* 149 zip */
    {0x82c330eu, 8, 1166}, /* 150 zipKeyed */
    {0xf38ddc0u, 6, 1175}, /* 151 Object */
    {0xbaea8f8u, 5, 1182}, /* 152 Array */
    {0x05c4cd7u, 5, 1188}, /* 153 Error */
    {0x519d1cau, 6, 1194}, /* 154 Number */
    {0x34b7feau, 6, 1201}, /* 155 String */
    {0xa75a0efu, 7, 1208}, /* 156 Boolean */
    {0xfb132d1u, 6, 1216}, /* 157 Symbol */
    {0x6906c3du, 9, 1223}, /* 158 Arguments */
    {0x10fdbb1u, 4, 1233}, /* 159 Math */
    {0xdc031e1u, 4, 1238}, /* 160 JSON */
    {0x74da49fu, 4, 1243}, /* 161 Date */
    {0x7ab23d1u, 8, 1248}, /* 162 Function */
    {0x1855bdau, 17, 1257}, /* 163 GeneratorFunction */
    {0x4ea15c3u, 13, 1275}, /* 164 ForInIterator */
    {0xa181442u, 6, 1289}, /* 165 RegExp */
    {0xbe38340u, 11, 1296}, /* 166 ArrayBuffer */
    {0x39959ebu, 17, 1308}, /* 167 SharedArrayBuffer */
    {0xeb01ab4u, 17, 1326}, /* 168 Uint8ClampedArray */
    {0x44405ffu, 9, 1344}, /* 169 Int8Array */
    {0x662965cu, 10, 1354}, /* 170 Uint8Array */
    {0x1a1fa56u, 10, 1365}, /* 171 Int16Array */
    {0xf0849e1u, 11, 1376}, /* 172 Uint16Array */
    {0x7c2cadcu, 10, 1388}, /* 173 Int32Array */
    {0x5291a67u, 11, 1399}, /* 174 Uint32Array */
    {0xb6f8c3bu, 13, 1411}, /* 175 BigInt64Array */
    {0xe172dfau, 14, 1425}, /* 176 BigUint64Array */
    {0x3b8c939u, 12, 1440}, /* 177 Float16Array */
    {0x9d999bfu, 12, 1453}, /* 178 Float32Array */
    {0x7b407c0u, 12, 1466}, /* 179 Float64Array */
    {0x9149548u, 8, 1479}, /* 180 DataView */
    {0x5776dd8u, 6, 1488}, /* 181 BigInt */
    {0xbe9da1au, 7, 1495}, /* 182 WeakRef */
    {0x47ba554u, 20, 1503}, /* 183 FinalizationRegistry */
    {0x1673d2bu, 3, 1524}, /* 184 Map */
    {0x16d9671u, 3, 1528}, /* 185 Set */
    {0xbe48f13u, 7, 1532}, /* 186 WeakMap */
    {0xbeae859u, 7, 1540}, /* 187 WeakSet */
    {0x120349fu, 8, 1548}, /* 188 Iterator */
    {0x26201bdu, 15, 1557}, /* 189 Iterator Concat */
    {0x27c611fu, 15, 1573}, /* 190 Iterator Helper */
    {0x197b953u, 13, 1589}, /* 191 Iterator Wrap */
    {0x6eb2cebu, 12, 1603}, /* 192 Map Iterator */
    {0x0fb1f55u, 12, 1616}, /* 193 Set Iterator */
    {0x88efac6u, 14, 1629}, /* 194 Array Iterator */
    {0xbdf27e4u, 15, 1644}, /* 195 String Iterator */
    {0xc617acfu, 22, 1660}, /* 196 RegExp String Iterator */
    {0x8b1234au, 9, 1683}, /* 197 Generator */
    {0x13686b5u, 5, 1693}, /* 198 Proxy */
    {0x184e262u, 7, 1699}, /* 199 Promise */
    {0x971520au, 22, 1707}, /* 200 PromiseResolveFunction */
    {0xe403999u, 21, 1730}, /* 201 PromiseRejectFunction */
    {0x75c4d3bu, 13, 1752}, /* 202 AsyncFunction */
    {0x72b5bd9u, 20, 1766}, /* 203 AsyncFunctionResolve */
    {0xe8041b2u, 19, 1787}, /* 204 AsyncFunctionReject */
    {0xfc82840u, 22, 1807}, /* 205 AsyncGeneratorFunction */
    {0x7b2af30u, 14, 1830}, /* 206 AsyncGenerator */
    {0x0778ebbu, 9, 1845}, /* 207 EvalError */
    {0x2fdbe5cu, 10, 1855}, /* 208 RangeError */
    {0x2f79d9eu, 14, 1866}, /* 209 ReferenceError */
    {0x3bc728cu, 11, 1881}, /* 210 SyntaxError */
    {0x6c4f8ddu, 9, 1893}, /* 211 TypeError */
    {0xe962805u, 8, 1903}, /* 212 URIError */
    {0xd11fe12u, 13, 1912}, /* 213 InternalError */
    {0x99e8b26u, 12, 1926}, /* 214 DOMException */
    {0x7b78596u, 8, 1939}, /* 215 CallSite */
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0, JS_ROM_NOT, 0},
    {0x8a7d615u, 9, 1948}, /* 230 ABORT_ERR */
    {0x84dee5au, 14, 1958}, /* 231 AggregateError */
    {0x73e7bcfu, 7, 1973}, /* 232 Atomics */
    {0x812fe0du, 17, 1981}, /* 233 BYTES_PER_ELEMENT */
    {0x4f862cfu, 14, 1999}, /* 234 DATA_CLONE_ERR */
    {0xf9f64acu, 18, 2014}, /* 235 DOMSTRING_SIZE_ERR */
    {0x7493f81u, 7, 2033}, /* 236 EPSILON */
    {0x1760842u, 21, 2041}, /* 237 HIERARCHY_REQUEST_ERR */
    {0xafb81adu, 14, 2063}, /* 238 INDEX_SIZE_ERR */
    {0xf538a44u, 19, 2078}, /* 239 INUSE_ATTRIBUTE_ERR */
    {0x505b1fbu, 18, 2098}, /* 240 INVALID_ACCESS_ERR */
    {0x9592a2eu, 21, 2117}, /* 241 INVALID_CHARACTER_ERR */
    {0x1dfbb13u, 24, 2139}, /* 242 INVALID_MODIFICATION_ERR */
    {0x2ec8d0cu, 21, 2164}, /* 243 INVALID_NODE_TYPE_ERR */
    {0x8812a96u, 17, 2186}, /* 244 INVALID_STATE_ERR */
    {0x2db7af1u | JS_ROM_NUMERIC, 8, 2204}, /* 245 Infinity */
    {0x83ad9d0u, 16, 2213}, /* 246 MAX_SAFE_INTEGER */
    {0x79da6adu, 9, 2230}, /* 247 MAX_VALUE */
    {0x7dfe152u, 16, 2240}, /* 248 MIN_SAFE_INTEGER */
    {0x3d6cebbu, 9, 2257}, /* 249 MIN_VALUE */
    {0xd137d68u, 13, 2267}, /* 250 NAMESPACE_ERR */
    {0x2464271u, 17, 2281}, /* 251 NEGATIVE_INFINITY */
    {0x5fbd923u, 11, 2299}, /* 252 NETWORK_ERR */
    {0xfe5f0d3u, 13, 2311}, /* 253 NOT_FOUND_ERR */
    {0x0e0f687u, 17, 2325}, /* 254 NOT_SUPPORTED_ERR */
    {0x45ac696u, 19, 2343}, /* 255 NO_DATA_ALLOWED_ERR */
    {0x0d4b360u, 27, 2363}, /* 256 NO_MODIFICATION_ALLOWED_ERR */
    {0x1684b3au, 3, 2391}, /* 257 NaN */
    {0x700709du, 17, 2395}, /* 258 POSITIVE_INFINITY */
    {0xc4641c1u, 18, 2413}, /* 259 QUOTA_EXCEEDED_ERR */
    {0xbc6e924u, 7, 2432}, /* 260 Reflect */
    {0x8e308bfu, 12, 2440}, /* 261 SECURITY_ERR */
    {0x5f9cfb2u, 10, 2453}, /* 262 SYNTAX_ERR */
    {0xd20ad9eu, 11, 2464}, /* 263 TIMEOUT_ERR */
    {0x74ed758u, 17, 2476}, /* 264 TYPE_MISMATCH_ERR */
    {0xa200b48u, 10, 2494}, /* 265 TypedArray */
    {0x275b415u, 16, 2505}, /* 266 URL_MISMATCH_ERR */
    {0x16fa12bu, 3, 2522}, /* 267 UTC */
    {0x82e5040u, 14, 2526}, /* 268 VALIDATION_ERR */
    {0xd1e4b24u, 18, 2541}, /* 269 WRONG_DOCUMENT_ERR */
    {0xd1c2357u, 16, 2560}, /* 270 __defineGetter__ */
    {0x8e282ebu, 16, 2577}, /* 271 __defineSetter__ */
    {0x291de46u, 16, 2594}, /* 272 __lookupGetter__ */
    {0xe583ddau, 16, 2611}, /* 273 __lookupSetter__ */
    {0x17c6448u, 3, 2628}, /* 274 all */
    {0x32b6391u, 10, 2632}, /* 275 allSettled */
    {0xe2a7e8eu, 6, 2643}, /* 276 anchor */
    {0x17c6663u, 3, 2650}, /* 277 any */
    {0x3d8c2c2u, 6, 2654}, /* 278 asIntN */
    {0xc46c259u, 7, 2661}, /* 279 asUintN */
    {0x15dc4d8u, 6, 2669}, /* 280 assign */
    {0x01ce229u, 13, 2676}, /* 281 asyncIterator */
    {0x001724cu, 2, 2690}, /* 282 at */
    {0x17d6f5fu, 3, 2693}, /* 283 big */
    {0x7dd722eu, 4, 2697}, /* 284 bind */
    {0x7bbce03u, 5, 2702}, /* 285 blink */
    {0x7e3c546u, 4, 2708}, /* 286 bold */
    {0x52e0139u, 6, 2713}, /* 287 buffer */
    {0xe8666ffu, 10, 2720}, /* 288 byteLength */
    {0x9d1388cu, 10, 2731}, /* 289 byteOffset */
    {0x8ea92f7u, 4, 2742}, /* 290 call */
    {0xd93d6f2u, 17, 2747}, /* 291 captureStackTrace */
    {0xc2fa192u, 6, 2765}, /* 292 charAt */
    {0x07af347u, 10, 2772}, /* 293 charCodeAt */
    {0x4e2ed4cu, 5, 2783}, /* 294 clear */
    {0x8f95166u, 4, 2789}, /* 295 code */
    {0x8ebd6bdu, 11, 2794}, /* 296 codePointAt */
    {0xd6de4e0u, 12, 2806}, /* 297 columnNumber */
    {0x60ad342u, 7, 2819}, /* 298 compile */
    {0x9eee6d9u, 10, 2827}, /* 299 copyWithin */
    {0x4262bcdu, 6, 2838}, /* 300 create */
    {0x517949du, 9, 2845}, /* 301 decodeURI */
    {0xbd94530u, 18, 2855}, /* 302 decodeURIComponent */
    {0xa8500d9u, 5, 2874}, /* 303 deref */
    {0xe53ba73u, 11, 2880}, /* 304 description */
    {0xa27e493u, 8, 2892}, /* 305 detached */
    {0xd49d896u, 10, 2901}, /* 306 difference */
    {0x45b0519u, 6, 2912}, /* 307 dotAll */
    {0xa121ba8u, 4, 2919}, /* 308 drop */
    {0xaa80b0du, 9, 2924}, /* 309 encodeURI */
    {0x0d59e40u, 18, 2934}, /* 310 encodeURIComponent */
    {0xf41ae8fu, 8, 2953}, /* 311 endsWith */
    {0x145feefu, 7, 2962}, /* 312 entries */
    {0xe50b1b2u, 6, 2970}, /* 313 escape */
    {0xa1194f2u, 5, 2977}, /* 314 every */
    {0x8eba4d0u, 8, 2983}, /* 315 fileName */
    {0xc33c184u, 4, 2992}, /* 316 fill */
    {0xc0a1c01u, 6, 2997}, /* 317 filter */
    {0xc33c38au, 4, 3004}, /* 318 find */
    {0x32ca470u, 9, 3009}, /* 319 findIndex */
    {0x8bf6a48u, 8, 3019}, /* 320 findLast */
    {0xb9c9e62u, 13, 3028}, /* 321 findLastIndex */
    {0x938721bu, 5, 3042}, /* 322 fixed */
    {0xc36e0d2u, 4, 3048}, /* 323 flat */
    {0x42b7832u, 7, 3053}, /* 324 flatMap */
    {0x1e89aa3u, 9, 3061}, /* 325 fontcolor */
    {0x32813a9u, 8, 3071}, /* 326 fontsize */
    {0x7eb8979u, 7, 3080}, /* 327 forEach */
    {0xae9deb0u, 6, 3088}, /* 328 freeze */
    {0x02170beu, 12, 3095}, /* 329 fromCharCode */
    {0x9e52bc0u, 13, 3108}, /* 330 fromCodePoint */
    {0x5b375edu, 11, 3122}, /* 331 fromEntries */
    {0x0ffb4cfu, 20, 3134}, /* 332 get [Symbol.species] */
    {0xb3773adu, 24, 3155}, /* 333 get [Symbol.toStringTag] */
    {0xbf7859du, 13, 3180}, /* 334 get __proto__ */
    {0x2f6615bu, 10, 3194}, /* 335 get buffer */
    {0x5163de1u, 14, 3205}, /* 336 get byteLength */
    {0x0610f6eu, 14, 3220}, /* 337 get byteOffset */
    {0x91c2128u, 8, 3235}, /* 338 get code */
    {0x3986222u, 16, 3244}, /* 339 get columnNumber */
    {0xc197ca1u, 15, 3261}, /* 340 get description */
    {0x2e62715u, 12, 3277}, /* 341 get detached */
    {0x223653bu, 10, 3290}, /* 342 get dotAll */
    {0x1a9e752u, 12, 3301}, /* 343 get fileName */
    {0x0245b24u, 9, 3314}, /* 344 get flags */
    {0xc178c5eu, 10, 3324}, /* 345 get global */
    {0x87275c8u, 12, 3335}, /* 346 get growable */
    {0x6d83898u, 14, 3348}, /* 347 get hasIndices */
    {0x77d121du, 14, 3363}, /* 348 get ignoreCase */
    {0x8f4693fu, 13, 3378}, /* 349 get immutable */
    {0x4c14e19u, 10, 3392}, /* 350 get length */
    {0x4632d80u, 14, 3403}, /* 351 get lineNumber */
    {0xf502d1fu, 17, 3418}, /* 352 get maxByteLength */
    {0xb99d1f4u, 11, 3436}, /* 353 get message */
    {0x7aef1bau, 13, 3448}, /* 354 get multiline */
    {0x4fac376u, 8, 3462}, /* 355 get name */
    {0x0246189u, 21, 3471}, /* 356 get prepareStackTrace */
    {0xe702028u, 13, 3493}, /* 357 get resizable */
    {0xa6f280cu, 8, 3507}, /* 358 get size */
    {0x529eb76u, 10, 3516}, /* 359 get source */
    {0x7beb6cbu, 19, 3527}, /* 360 get stackTraceLimit */
    {0x9f025b4u, 10, 3547}, /* 361 get sticky */
    {0xcb162bau, 11, 3558}, /* 362 get unicode */
    {0xcd1f3a3u, 15, 3570}, /* 363 get unicodeSets */
    {0x214ab4au, 11, 3586}, /* 364 getBigInt64 */
    {0x620c60bu, 12, 3598}, /* 365 getBigUint64 */
    {0xf205cc4u, 15, 3611}, /* 366 getColumnNumber */
    {0xf940463u, 7, 3627}, /* 367 getDate */
    {0x76ba297u, 6, 3635}, /* 368 getDay */
    {0xf394334u, 11, 3642}, /* 369 getFileName */
    {0xf1f2274u, 10, 3654}, /* 370 getFloat16 */
    {0xf1f247eu, 10, 3665}, /* 371 getFloat32 */
    {0xf1f2795u, 10, 3676}, /* 372 getFloat64 */
    {0x21b17e1u, 11, 3687}, /* 373 getFullYear */
    {0x809c115u, 11, 3699}, /* 374 getFunction */
    {0x9607568u, 15, 3711}, /* 375 getFunctionName */
    {0x4ed4ffau, 8, 3727}, /* 376 getHours */
    {0x101cfcfu, 8, 3736}, /* 377 getInt16 */
    {0x101d1d9u, 8, 3745}, /* 378 getInt32 */
    {0x50da266u, 7, 3754}, /* 379 getInt8 */
    {0xfbc1fc2u, 13, 3762}, /* 380 getLineNumber */
    {0xd057457u, 15, 3776}, /* 381 getMilliseconds */
    {0x87f0c8au, 10, 3792}, /* 382 getMinutes */
    {0x6bee98bu, 8, 3803}, /* 383 getMonth */
    {0x5636319u, 11, 3812}, /* 384 getOrInsert */
    {0x7e97506u, 19, 3824}, /* 385 getOrInsertComputed */
    {0x000ab26u, 25, 3844}, /* 386 getOwnPropertyDescriptors */
    {0xf237a22u, 19, 3870}, /* 387 getOwnPropertyNames */
    {0x676e19du, 21, 3890}, /* 388 getOwnPropertySymbols */
    {0x02587f2u, 10, 3912}, /* 389 getSeconds */
    {0x0f5b42au, 7, 3923}, /* 390 getTime */
    {0xf109679u, 17, 3931}, /* 391 getTimezoneOffset */
    {0xf992325u, 10, 3949}, /* 392 getUTCDate */
    {0x864d745u, 9, 3960}, /* 393 getUTCDay */
    {0xdc44963u, 14, 3970}, /* 394 getUTCFullYear */
    {0xa2fe948u, 11, 3985}, /* 395 getUTCHours */
    {0x37f8099u, 18, 3997}, /* 396 getUTCMilliseconds */
    {0x7eea878u, 13, 4016}, /* 397 getUTCMinutes */
    {0xc0182d9u, 11, 4030}, /* 398 getUTCMonth */
    {0xf9523e0u, 13, 4042}, /* 399 getUTCSeconds */
    {0xbc68a74u, 9, 4056}, /* 400 getUint16 */
    {0xbc68c7eu, 9, 4066}, /* 401 getUint32 */
    {0x9989a59u, 8, 4076}, /* 402 getUint8 */
    {0x65d54d2u, 7, 4085}, /* 403 getYear */
    {0x57f0635u, 7, 4093}, /* 404 groupBy */
    {0xd52d8b4u, 4, 4101}, /* 405 grow */
    {0xfb43346u, 8, 4106}, /* 406 growable */
    {0x04861b6u, 10, 4115}, /* 407 hasIndices */
    {0xad547eeu, 11, 4126}, /* 408 hasInstance */
    {0x949520du, 6, 4138}, /* 409 hasOwn */
    {0x77e7632u, 14, 4145}, /* 410 hasOwnProperty */
    {0x0ed3b3bu, 10, 4160}, /* 411 ignoreCase */
    {0xd7e15b1u, 9, 4171}, /* 412 immutable */
    {0x540edfcu, 8, 4181}, /* 413 includes */
    {0x971b4f0u, 7, 4190}, /* 414 indexOf */
    {0x7890f72u, 12, 4198}, /* 415 intersection */
    {0x0017a83u, 2, 4211}, /* 416 is */
    {0x07edfc6u, 7, 4214}, /* 417 isArray */
    {0xd93f8dcu, 18, 4222}, /* 418 isConcatSpreadable */
    {0x396e601u, 14, 4241}, /* 419 isDisjointFrom */
    {0x52c83a5u, 7, 4256}, /* 420 isError */
    {0xd6d30b2u, 8, 4264}, /* 421 isFinite */
    {0x51b3753u, 8, 4273}, /* 422 isFrozen */
    {0xa673fb3u, 9, 4282}, /* 423 isInteger */
    {0xb661568u, 5, 4292}, /* 424 isNaN */
    {0x73cb6fau, 8, 4298}, /* 425 isNative */
    {0xee3fe26u, 13, 4307}, /* 426 isPrototypeOf */
    {0xa73d4f6u, 13, 4321}, /* 427 isSafeInteger */
    {0xd3d2467u, 8, 4335}, /* 428 isSealed */
    {0xc9a13b4u, 10, 4344}, /* 429 isSubsetOf */
    {0x8c887d9u, 12, 4355}, /* 430 isSupersetOf */
    {0xe952a30u, 6, 4368}, /* 431 isView */
    {0xa699574u, 12, 4375}, /* 432 isWellFormed */
    {0x6f5bad2u, 7, 4388}, /* 433 italics */
    {0xb31337fu, 8, 4396}, /* 434 iterator */
    {0xb2e4da3u, 6, 4405}, /* 435 keyFor */
    {0x89097a2u, 11, 4412}, /* 436 lastIndexOf */
    {0xdd3569eu, 10, 4424}, /* 437 lineNumber */
    {0x2b53d9bu, 4, 4435}, /* 438 link */
    {0xd616a12u, 13, 4440}, /* 439 localeCompare */
    {0x189034bu, 3, 4454}, /* 440 map */
    {0xcb75a3cu, 5, 4458}, /* 441 match */
    {0x5ab6435u, 8, 4464}, /* 442 matchAll */
    {0xc389e2cu, 9, 4473}, /* 443 multiline */
    {0xe023144u, 9, 4483}, /* 444 normalize */
    {0x18a1fe5u, 3, 4493}, /* 445 now */
    {0x5a43ef9u, 6, 4497}, /* 446 padEnd */
    {0xdb8fc00u, 8, 4504}, /* 447 padStart */
    {0x4377e6au, 5, 4513}, /* 448 parse */
    {0x6170bbau, 10, 4519}, /* 449 parseFloat */
    {0xcf0bb75u, 8, 4530}, /* 450 parseInt */
    {0x8d0f20fu, 11, 4539}, /* 451 performance */
    {0x18c3c40u, 3, 4551}, /* 452 pop */
    {0x66adf7bu, 17, 4555}, /* 453 prepareStackTrace */
    {0x30b9df0u, 20, 4573}, /* 454 propertyIsEnumerable */
    {0x7183e63u, 4, 4594}, /* 455 push */
    {0xfa16c81u, 14, 4599}, /* 456 queueMicrotask */
    {0x92e3acau, 4, 4614}, /* 457 race */
    {0x9aebfafu, 6, 4619}, /* 458 reduce */
    {0x57b76edu, 11, 4626}, /* 459 reduceRight */
    {0x2bd786cu, 8, 4638}, /* 460 register */
    {0x6a0ceb4u, 6, 4647}, /* 461 repeat */
    {0x6cb583bu, 7, 4654}, /* 462 replace */
    {0x63921deu, 10, 4662}, /* 463 replaceAll */
    {0x2f9cc9au, 9, 4673}, /* 464 resizable */
    {0x9e5de1du, 6, 4683}, /* 465 resize */
    {0xe4aabd1u, 7, 4690}, /* 466 reverse */
    {0x042b980u, 9, 4698}, /* 467 revocable */
    {0xa4805deu, 4, 4708}, /* 468 seal */
    {0xdfffec1u, 6, 4713}, /* 469 search */
    {0x9a9a141u, 24, 4720}, /* 470 set [Symbol.toStringTag] */
    {0x9b3d729u, 13, 4745}, /* 471 set __proto__ */
    {0xbcf0415u, 21, 4759}, /* 472 set prepareStackTrace */
    {0x6c8e317u, 19, 4781}, /* 473 set stackTraceLimit */
    {0xce4b696u, 11, 4801}, /* 474 setBigInt64 */
    {0x1dc611fu, 12, 4813}, /* 475 setBigUint64 */
    {0xa54872fu, 7, 4826}, /* 476 setDate */
    {0x8e585c8u, 10, 4834}, /* 477 setFloat16 */
    {0x8e587d2u, 10, 4845}, /* 478 setFloat32 */
    {0x8e58ae9u, 10, 4856}, /* 479 setFloat64 */
    {0xceb232du, 11, 4867}, /* 480 setFullYear */
    {0x0b3af8eu, 8, 4879}, /* 481 setHours */
    {0xcc82f63u, 8, 4888}, /* 482 setInt16 */
    {0xcc8316du, 8, 4897}, /* 483 setInt32 */
    {0xfce2532u, 7, 4906}, /* 484 setInt8 */
    {0xc12b823u, 15, 4914}, /* 485 setMilliseconds */
    {0x2456fdeu, 10, 4930}, /* 486 setMinutes */
    {0x285491fu, 8, 4941}, /* 487 setMonth */
    {0x9ebeb46u, 10, 4950}, /* 488 setSeconds */
    {0xbb636f6u, 7, 4961}, /* 489 setTime */
    {0x95f8679u, 10, 4969}, /* 490 setUTCDate */
    {0xa3c1037u, 14, 4980}, /* 491 setUTCFullYear */
    {0x4fff494u, 11, 4995}, /* 492 setUTCHours */
    {0x7ef7aedu, 18, 5007}, /* 493 setUTCMilliseconds */
    {0x5aafa04u, 13, 5026}, /* 494 setUTCMinutes */
    {0x6d18e25u, 11, 5040}, /* 495 setUTCMonth */
    {0xd51756cu, 13, 5052}, /* 496 setUTCSeconds */
    {0x492bb80u, 9, 5066}, /* 497 setUint16 */
    {0x492bd8au, 9, 5076}, /* 498 setUint32 */
    {0x55ef9edu, 8, 5086}, /* 499 setUint8 */
    {0x11dd79eu, 7, 5095}, /* 500 setYear */
    {0x3472fe9u, 5, 5103}, /* 501 shift */
    {0x79d7e21u, 5, 5109}, /* 502 slice */
    {0x20e579eu, 16, 5115}, /* 503 sliceToImmutable */
    {0x8aaaa36u, 5, 5132}, /* 504 small */
    {0xa52a015u, 4, 5138}, /* 505 some */
    {0xa52a547u, 4, 5143}, /* 506 sort */
    {0x9d79863u, 7, 5148}, /* 507 species */
    {0xac139edu, 6, 5156}, /* 508 splice */
    {0x679fd5du, 15, 5163}, /* 509 stackTraceLimit */
    {0x07588f0u, 10, 5179}, /* 510 startsWith */
    {0xc27c592u, 6, 5190}, /* 511 sticky */
    {0x5f051b3u, 6, 5197}, /* 512 strike */
    {0x18f6cefu, 3, 5204}, /* 513 sub */
    {0x85cb85au, 8, 5208}, /* 514 subarray */
    {0x1cd08dau, 6, 5217}, /* 515 substr */
    {0xa1d4d98u, 9, 5224}, /* 516 substring */
    {0x18f6cfdu, 3, 5234}, /* 517 sup */
    {0x339d4bbu, 19, 5238}, /* 518 symmetricDifference */
    {0xb596bb0u, 4, 5258}, /* 519 take */
    {0xb5dacbbu, 4, 5263}, /* 520 test */
    {0xdc90114u, 10, 5268}, /* 521 timeOrigin */
    {0x2b01265u, 7, 5279}, /* 522 toArray */
    {0x2786783u, 12, 5287}, /* 523 toDateString */
    {0x08f8b91u, 13, 5300}, /* 524 toExponential */
    {0xacd2f68u, 7, 5314}, /* 525 toFixed */
    {0xfdb3653u, 11, 5322}, /* 526 toGMTString */
    {0xc1037cau, 11, 5334}, /* 527 toISOString */
    {0x98dc555u, 18, 5346}, /* 528 toLocaleDateString */
    {0xcf9cf73u, 17, 5365}, /* 529 toLocaleLowerCase */
    {0xc40080cu, 18, 5383}, /* 530 toLocaleTimeString */
    {0xe48853cu, 17, 5402}, /* 531 toLocaleUpperCase */
    {0x365c655u, 11, 5420}, /* 532 toLowerCase */
    {0x388b51au, 11, 5432}, /* 533 toPrecision */
    {0x95ca963u, 11, 5444}, /* 534 toPrimitive */
    {0xa045d46u, 10, 5456}, /* 535 toReversed */
    {0x3f166d9u, 8, 5467}, /* 536 toSorted */
    {0x9a1f49cu, 9, 5476}, /* 537 toSpliced */
    {0x196bff5u, 11, 5486}, /* 538 toStringTag */
    {0x52aaa3au, 12, 5498}, /* 539 toTimeString */
    {0xc6c6e01u, 11, 5511}, /* 540 toUTCString */
    {0x4b47c1eu, 11, 5523}, /* 541 toUpperCase */
    {0x590352du, 12, 5535}, /* 542 toWellFormed */
    {0x0a50d04u, 8, 5548}, /* 543 transfer */
    {0xe87ee03u, 21, 5557}, /* 544 transferToFixedLength */
    {0xecca483u, 19, 5579}, /* 545 transferToImmutable */
    {0xb6b5aebu, 4, 5599}, /* 546 trim */
    {0x29c0678u, 7, 5604}, /* 547 trimEnd */
    {0x5d83672u, 8, 5612}, /* 548 trimLeft */
    {0x47ba311u, 9, 5621}, /* 549 trimRight */
    {0xd8e1d4fu, 9, 5631}, /* 550 trimStart */
    {0x8d9d313u, 8, 5641}, /* 551 unescape */
    {0xf0c3175u, 11, 5650}, /* 552 unicodeSets */
    {0x41f7deeu, 5, 5662}, /* 553 union */
    {0x83129fdu, 10, 5668}, /* 554 unregister */
    {0xcfc4456u, 11, 5679}, /* 555 unscopables */
    {0xcee2840u, 7, 5691}, /* 556 unshift */
    {0x3c1f4f6u, 13, 5699}, /* 557 withResolvers */
};

static const uint16_t js_rom_hash[1u << JS_ROM_HASH_BITS] = {
    0,0,0,106,0,212,0,0,0,0,0,0,358,530,0,0,
    0,0,0,0,0,505,0,0,0,0,0,0,0,0,0,0,
    0,0,24,485,0,0,0,0,357,0,0,0,0,0,0,0,
    0,0,324,0,0,0,0,491,0,0,0,462,0,0,0,0,
    205,268,237,556,0,0,0,0,0,94,49,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,187,514,0,0,0,0,0,
    0,0,0,507,0,76,0,0,0,0,0,0,460,0,0,0,
    0,0,0,0,0,0,0,0,397,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,289,0,0,0,
    0,0,0,0,0,129,306,0,347,396,0,0,0,258,0,0,
    68,0,0,0,0,146,0,0,0,0,0,0,0,0,0,0,
    0,0,421,0,405,0,0,0,0,0,0,0,0,0,329,261,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,323,253,0,0,0,0,143,303,515,0,418,211,0,135,
    82,0,0,0,0,0,130,0,0,0,0,0,0,0,0,156,
    510,0,0,0,0,0,0,0,152,0,0,0,0,10,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,101,0,0,521,374,0,0,0,0,0,0,0,0,0,190,
    475,487,0,252,260,0,0,0,338,0,0,267,0,0,0,0,
    0,128,0,0,0,0,0,0,0,177,39,287,0,0,0,349,
    0,470,0,0,444,0,0,0,395,0,0,0,0,0,0,0,
    0,0,248,191,0,0,0,0,0,0,0,335,0,0,0,0,
    0,0,0,394,534,0,295,0,0,0,0,0,0,483,0,0,
    0,0,0,0,0,552,0,0,0,327,0,0,0,0,0,0,
    467,0,0,0,316,42,0,0,0,356,0,383,0,0,0,0,
    0,0,292,0,0,138,0,0,0,201,0,108,0,388,0,0,
    0,0,0,0,0,0,0,58,0,0,0,0,0,238,0,0,
    0,0,204,313,512,0,407,0,0,0,354,0,0,46,116,178,
    189,259,0,0,0,0,0,0,0,0,154,0,0,0,0,0,
    246,0,0,0,0,0,0,0,0,378,0,0,45,0,463,0,
    0,160,172,0,0,0,0,0,22,0,0,167,0,499,18,508,
    0,0,0,0,353,103,0,44,0,0,0,240,0,554,0,0,
    0,0,0,0,494,0,0,0,0,0,200,136,0,409,0,69,
    451,0,439,0,0,0,0,0,0,0,182,322,0,348,0,0,
    0,21,339,387,0,0,0,0,0,281,0,0,0,0,241,284,
    19,431,0,0,0,0,504,0,0,0,539,0,441,0,0,0,
    0,0,0,0,239,66,0,113,320,0,0,123,282,0,0,0,
    0,0,0,0,0,0,171,0,0,279,402,0,0,59,0,0,
    0,0,199,0,0,522,379,174,0,0,0,0,0,0,0,0,
    0,251,0,99,304,370,4,400,0,0,0,0,0,0,13,0,
    0,0,0,416,0,0,0,0,0,0,0,0,210,0,0,0,
    0,0,0,0,0,0,244,368,0,0,0,0,0,0,0,0,
    74,0,36,325,0,141,0,0,0,63,0,0,0,0,0,0,
    0,27,127,0,168,0,0,0,0,0,362,0,0,0,0,0,
    0,0,278,0,0,0,194,0,0,0,41,457,147,0,0,196,
    234,157,137,433,0,134,110,0,0,398,0,0,173,0,0,0,
    0,0,0,0,0,0,0,0,119,479,0,271,546,493,139,0,
    0,245,0,0,0,0,0,290,0,0,26,0,0,0,0,0,
    0,0,0,0,0,0,7,0,0,0,0,0,0,309,150,72,
    52,549,0,242,551,0,0,473,0,384,0,0,0,0,0,0,
    0,0,0,0,269,344,214,386,392,0,117,0,0,480,0,0,
    0,0,0,0,369,0,0,0,0,0,257,411,0,0,0,0,
    166,0,298,0,0,0,406,293,265,488,197,364,440,0,0,0,
    0,0,0,0,109,91,0,270,0,60,0,0,0,0,0,0,
    256,0,0,0,0,0,0,0,0,125,0,0,0,0,0,79,
    0,0,0,0,0,450,355,359,0,0,2,0,80,0,0,29,
    434,497,142,86,0,0,0,0,16,0,318,0,0,0,0,0,
    0,275,524,0,0,0,95,0,65,0,0,0,0,0,0,0,
    0,0,28,363,0,93,420,0,308,326,0,0,9,333,0,0,
    519,159,0,0,55,429,0,0,0,0,449,0,0,0,0,0,
    330,0,0,0,0,0,0,0,0,0,0,0,0,300,0,232,
    0,162,466,0,0,48,0,81,0,203,163,0,0,0,0,0,
    399,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,57,0,0,0,0,0,0,0,0,
    149,317,447,0,0,0,0,0,105,0,0,118,0,0,0,0,
    0,0,121,0,0,266,472,0,0,0,0,0,0,0,541,0,
    0,0,0,0,0,0,0,0,0,0,390,0,0,0,0,0,
    0,88,0,0,0,442,0,0,0,0,0,175,111,158,0,0,
    452,0,165,0,0,0,0,0,274,0,0,0,0,0,0,0,
    0,0,0,124,0,40,555,381,0,100,0,0,0,78,345,0,
    122,0,0,367,0,0,0,114,428,0,0,0,0,0,0,0,
    319,0,25,0,0,0,0,0,0,0,0,0,0,0,371,401,
    0,456,133,545,0,0,0,0,0,0,31,382,0,0,0,0,
    0,6,67,305,492,0,0,0,0,0,464,0,537,301,0,161,
    188,340,0,0,0,0,0,0,0,37,0,0,235,0,0,70,
    0,0,0,0,0,0,0,0,0,104,0,518,520,0,0,0,
    0,0,0,0,366,0,0,0,0,0,73,0,0,0,0,332,
    315,0,403,0,0,0,0,153,280,0,0,0,0,0,0,0,
    297,0,0,0,0,0,0,0,0,0,0,192,0,0,0,513,
    414,0,314,92,0,0,427,557,0,0,0,0,0,517,0,0,
    0,0,0,131,543,14,385,8,0,0,0,0,243,0,0,0,
    0,0,0,0,0,0,0,0,0,307,533,0,0,0,0,352,
    0,0,0,0,0,0,0,0,0,0,0,184,0,542,98,0,
    302,0,484,0,0,0,0,0,0,0,0,202,342,531,35,0,
    0,0,0,0,0,0,286,506,180,535,0,0,294,0,0,550,
    0,0,0,0,183,528,0,0,0,0,0,0,15,509,0,0,
    0,0,32,0,0,0,0,0,250,375,424,0,496,0,0,0,
    0,0,0,0,432,0,0,0,0,0,0,0,0,0,0,0,
    351,0,0,0,0,0,0,0,0,0,498,0,0,0,0,0,
    0,0,511,0,0,0,215,0,516,0,0,438,0,334,209,12,
    263,102,0,435,0,0,0,0,0,0,0,0,0,0,0,0,
    38,412,0,0,361,0,0,0,0,0,0,0,0,0,0,0,
    151,0,0,164,0,85,0,0,346,477,0,0,0,33,0,0,
    0,0,0,0,0,0,0,0,181,77,273,0,0,0,468,0,
    0,336,0,0,0,0,0,0,0,0,11,120,0,331,553,0,
    454,0,0,0,0,0,0,50,0,0,176,0,413,0,0,169,
    0,419,540,285,544,0,0,0,0,0,0,365,0,233,0,0,
    0,0,213,0,0,230,0,0,0,350,0,0,0,465,0,0,
    0,502,0,0,0,495,426,0,0,0,0,0,443,0,0,0,
    0,61,43,410,53,404,0,0,0,0,0,0,0,0,0,0,
    310,0,0,0,0,23,272,0,0,0,0,0,0,0,0,0,
    0,148,0,526,0,532,0,0,17,0,231,140,170,208,0,0,
    0,0,321,277,455,0,0,0,97,0,448,0,0,0,0,0,
    0,185,548,0,0,0,0,0,547,391,490,0,0,0,0,0,
    0,144,0,0,0,0,0,254,1,0,0,0,0,0,276,311,
    0,0,0,0,0,0,255,474,0,0,0,0,0,0,437,0,
    0,0,0,0,0,0,0,0,0,64,71,0,0,20,247,0,
    328,0,0,0,461,198,0,0,132,0,0,207,249,296,0,0,
    0,469,0,0,0,0,0,0,0,0,0,360,0,0,0,0,
    0,0,0,0,0,0,0,0,0,299,536,0,0,0,0,0,
    0,0,0,84,0,56,0,0,0,89,5,0,0,459,0,312,
    0,0,291,0,0,0,489,90,34,446,425,0,0,0,0,288,
    0,0,0,0,0,0,51,30,0,0,0,0,0,0,0,0,
    0,0,0,186,0,341,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,471,0,0,0,0,0,476,
    206,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,
    0,0,0,0,0,393,0,0,0,0,0,0,0,0,126,0,
    0,0,343,422,0,193,0,54,264,0,0,0,0,0,0,283,
    0,0,0,482,0,0,0,0,525,0,83,0,0,0,337,0,
    0,0,415,529,0,0,0,0,0,0,0,453,0,0,0,0,
    0,236,0,523,0,0,0,0,0,0,0,0,0,0,481,0,
    115,0,0,0,96,372,0,0,0,0,0,0,0,0,500,503,
    0,0,436,0,0,0,0,0,0,0,62,87,0,0,0,458,
    0,75,262,423,0,0,0,0,0,0,0,0,0,0,0,145,
    179,0,380,0,0,0,417,0,0,0,527,0,112,0,0,377,
    0,0,478,0,107,0,0,0,0,430,0,0,0,0,486,0,
    0,373,0,0,195,445,0,0,0,501,155,0,0,0,408,0,
    0,0,389,0,0,538,0,0,0,0,376,0,0,0,0,0,
};
