"""Regenerate the diagnostic C strings from the real symbolic JS sources."""

from pathlib import Path
import argparse
import json


ROOT = Path(__file__).resolve().parents[2]
SOURCES = (
    ("grid_fold_js", ROOT / "apps/kasane/grid_fold.js"),
    ("grid_fold_device_js", ROOT / "apps/kasane/grid_fold_device_probe.js"),
)
OUTPUT = ROOT / "main/ui/kasane/ksn_grid_fold_device_assets.h"


def generate() -> str:
    lines = ["/* Generated by make_grid_fold_device_assets.py; do not edit. */",
             "#ifndef KSN_GRID_FOLD_DEVICE_ASSETS_H",
             "#define KSN_GRID_FOLD_DEVICE_ASSETS_H"]
    for name, path in SOURCES:
        lines.append(f"static const char {name}[] =")
        for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
            lines.append("    " + json.dumps(line, ensure_ascii=True) + "")
        lines.append("    ;")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("grid device JS assets are stale")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
