#!/usr/bin/env python3
"""Generate the quarter-turn cosine table main/scene/fxmath.c interpolates.

The table is cos(k*h) * 2^scale for k = 0..N, h = (pi/2)/N, i.e. one quadrant at
N intervals (N+1 entries; the last one is exactly zero and is what the sine's
interval needs). Q31 (int32, scale 31) or Q15 (int16, scale 15) as asked.

  python3 tools/gen_fx_lut.py --intervals 512 --type q31 --out main/scene/fx_lut_gen.h

The output is committed: it is small, it is the thing the image depends on, and a
build-time generator would make the firmware depend on a host Python.
"""
import argparse
import math

QMAX = {31: (1 << 31) - 1, 15: (1 << 15) - 1}


def entries(n, scale, shift=0, count=None):
    h = (math.pi / 2) / n
    one = 1 << scale
    hi = QMAX[scale]
    if count is None:
        count = n + 1
    out = []
    for m in range(count):
        k = m + shift
        v = int(round(math.cos(k * h) * one))
        if v > hi:
            v = hi
        out.append(v)
    return out


def wrap_type(scale):
    return "int32_t" if scale == 31 else "int16_t"


def emit(n, scale, order, out):
    if order == 2:
        # Three-point Lagrange needs the node before j as well, so the table is
        # stored shifted by one: entry m is cos((m-1)*h), m = 0..n+1. That puts
        # cos(-h) at 0 and keeps every index the interpolation asks for
        # (j-1..j+1 for j <= n-1, and the same for the sine's interval) inside
        # the array.
        vals = entries(n, scale, shift=-1, count=n + 2)
    else:
        vals = entries(n, scale)
    lines = []
    lines.append("// Generated by tools/gen_fx_lut.py -- do not edit by hand.")
    lines.append("//")
    if order == 2:
        lines.append("// cos((m-1)*h)*2^%d for h = (pi/2)/%d, m = 0..%d: the quadrant's cosine" % (scale, n, n + 1))
        lines.append("// shifted one place, so that a three-point Lagrange over the nodes")
        lines.append("// (j-1, j, j+1) can read entry m=j as the left node. The last entry is 0.")
    else:
        lines.append("// cos(k*h)*2^%d for h = (pi/2)/%d, k = 0..%d. The last entry is exactly" % (scale, n, n))
        lines.append("// zero: it is the right end of the sine's interval, which is this table read")
        lines.append("// backwards -- sin(jh+t*h) = cos((%d-j-(1-t))*h)." % n)
    lines.append("//")
    if order == 2:
        lines.append("// The angle-zero entry is index 1 here (the array is shifted), and it is %d" % QMAX[scale])
        lines.append("// rather than 2^%d: the exact value does not fit the type, and %d converts" % (scale, QMAX[scale]))
        lines.append("// to 1.0f exactly anyway.")
    else:
        lines.append("// Entry 0 is %d rather than 2^%d: the exact value does not fit the type," % (QMAX[scale], scale))
        lines.append("// and %d converts to 1.0f exactly anyway." % QMAX[scale])
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define FX_LUT_INTERVALS %d" % n)
    lines.append("#define FX_LUT_ENTRIES %d" % len(vals))
    lines.append("#define FX_LUT_ORDER %d" % order)
    lines.append("#define FX_LUT_SHIFT %d" % scale)
    lines.append("#define FX_LUT_TYPE %s" % wrap_type(scale))
    lines.append("")
    lines.append("static const FX_LUT_TYPE fx_quarter[FX_LUT_ENTRIES] = {")
    per = 8 if scale == 31 else 10
    width = 12 if scale == 31 else 7
    for i in range(0, len(vals), per):
        chunk = vals[i:i + per]
        lines.append("    " + " ".join(("%*d," % (width, v)) for v in chunk).rstrip())
    lines.append("};")
    lines.append("")
    text = "\n".join(lines)
    with open(out, "w") as f:
        f.write(text)
    print("wrote %s: intervals=%d entries=%d order=%d type=%s %d bytes" %
          (out, n, len(vals), order, wrap_type(scale),
           4 * len(vals) if scale == 31 else 2 * len(vals)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--intervals", type=int, required=True,
                    help="intervals per quadrant; the table has intervals+1 entries")
    ap.add_argument("--type", choices=["q31", "q15"], required=True)
    ap.add_argument("--order", type=int, choices=[1, 2], default=1,
                    help="1 = linear interpolation, 2 = three-point Lagrange")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    emit(a.intervals, 31 if a.type == "q31" else 15, a.order, a.out)


if __name__ == "__main__":
    main()
