"""Bake the home screen's three constant scene tables into flash.

sine, softness and wave_lut were built once by shell.c's build_tables() and
never written again. build_tables() reads nothing -- no tilt, no clock, no
setting -- so all three are functions of literals, and 1,484 B of .bss was
being spent on values a compiler could have known. Emitted as `const` they land
in .rodata: flash, reached through the instruction cache, costing no DRAM.

Same shape as tools/make_sfx.py, and for the same reason. The arithmetic is a
transcription of build_tables(), not a re-derivation of it: f32() rounds after
every operation so the float steps happen in the same order and at the same
precision the device used to use. Two libm implementations do not have to
return the same sinf or expf, so tools/test_scene_tables.py measures what is
left over rather than asserting it is zero.

The fourth table build_tables() filled, ocean_cols plane 2 (|x-160|), is not
here: it is constant too, but it lives inside the ocean's 16-byte-aligned
column block and cannot be split out of it. It stays a 240-store loop on the
rebuild path, which is where the rest of that block is filled anyway.

tools/pie/test_kernels.py imports sine() and softness() from here rather than
rebuilding them, so the tables the kernel simulation compares against are the
same values the device holds.
"""
import struct
import sys
import math
from pathlib import Path

LCD_H = 135
WIDTHS = (18.0, 5.0, 24.0)
BRIGHTNESS = (14.0, 32.0, 21.0)


def f32(x):
    """Round to single precision, as every step of the C reference does."""
    return struct.unpack('<f', struct.pack('<f', x))[0]


def sinf(x):
    return f32(math.sin(f32(x)))


def expf(x):
    return f32(math.exp(f32(x)))


def sine():
    """sine[i] = (int16_t)(sinf(i*6.2831853f/256)*256), truncating toward zero."""
    return [int(f32(sinf(f32(f32(i * f32(6.2831853)) / f32(256))) * f32(256)))
            for i in range(256)]


def softness():
    """softness[l][d] = (uint8_t)(brightness[l]*expf(-d*d/(2*w*w)))."""
    out = []
    for l in range(3):
        w = f32(WIDTHS[l])
        denom = f32(f32(2.0 * w) * w)
        out.append([int(f32(f32(BRIGHTNESS[l]) * expf(f32(-f32(d * d) / denom))))
                    for d in range(64)])
    return out


def wave_lut():
    """The softness of a row and its channel weight, packed into one word.

    Entry 64 is zero, which is how "further than 64 rows away" stops being a
    branch in the vector row.
    """
    soft = softness()
    out = []
    for l in range(3):
        row = []
        for d in range(64):
            lo = soft[l][d]
            hi = lo // 4 if l == 0 else lo // 3 if l == 1 else lo // 2
            row.append(lo | (hi << 16))
        row.append(0)
        out.append(row)
    return out


def rows(values, per_line=16):
    return ',\n'.join(','.join(str(v) for v in values[i:i + per_line])
                      for i in range(0, len(values), per_line))


def emit(name, values, ctype, dims=None):
    """One table, with the declared shape kept so every index in the kernels
    reads unchanged. Nested tables get their inner braces written out rather
    than relying on brace elision: the firmware builds with -Wmissing-braces
    promoted to an error, so elision is a build failure here, not a style."""
    if dims is None:
        return f'static const {ctype} {name}[{len(values)}] = {{\n{rows(values)}\n}};\n'
    shape = ''.join(f'[{d}]' for d in dims)
    inner = ',\n'.join('{\n' + rows(row) + '\n}' for row in values)
    return f'static const {ctype} {name}{shape} = {{\n{inner}\n}};\n'


def generate(out):
    out.mkdir(parents=True, exist_ok=True)
    text = ('// Generated by tools/make_scene_tables.py. Do not edit.\n'
            '#pragma once\n#include <stdint.h>\n')
    text += emit('sine', sine(), 'int16_t')
    # Kept as the 2-D shapes the kernels index, so no use site changes.
    text += emit('softness', softness(), 'uint8_t', (3, 64))
    text += emit('wave_lut', wave_lut(), 'uint32_t', (3, 65))
    (out / 'scene_tables.h').write_text(text, encoding='utf-8')


if __name__ == '__main__':
    generate(Path(sys.argv[1]))
