"""Bake the three click effects and the tone sine table into flash.

Both tables were built once at sound_init() and never written again, which cost
9,152 B of .bss on a board whose whole DIRAM is 341,760 B and which cannot run
TLS from an app for want of ~48 KB. Nothing in either table depends on anything
known only at run time -- not volume, not mute state -- so they are produced
here and emitted as `const`, which lands them in .rodata: flash, reached through
the instruction cache, costing no DRAM at all.

The arithmetic below is a transcription of main/hal/sfx_synth.h, which is the
reference the device used to run. It is transcribed rather than shared because
this side is Python; f32() rounds after every operation so the two agree to the
last float step, and tools/test_sfx.py measures what is left over rather than
assuming it is zero -- two libm implementations do not have to return the same
sinf, and the check exists to say by how much.

The click PCM is emitted flat. The device held it as a rectangular [3][1440]
while the real lengths are {720,1440,1080}; the rectangle's 2,160 B of padding
buys nothing once an offset table indexes it, and the indexing is the same one
add either way.
"""
import math
import struct
import sys
from pathlib import Path

SAMPLE_RATE = 24000
SFX_FRAMES = (720, 1440, 1080)
WAVE_POINTS = 256
WAVE_PEAK = 12000


def f32(x):
    """Round to single precision, as every step of the C reference does."""
    return struct.unpack('<f', struct.pack('<f', x))[0]


def sinf(x):
    return f32(math.sin(f32(x)))


def click(kind):
    """One effect, in the order main/hal/sfx_synth.h evaluates it."""
    frames = SFX_FRAMES[kind]
    frequency = f32(880.0 if kind == 1 else 440.0 if kind == 2 else 660.0)
    phase = f32(0.0)
    out = []
    for n in range(frames):
        u = f32(f32(n) / f32(frames))
        envelope = f32(f32(min(f32(f32(n) / f32(72.0)), f32(1.0)) * f32(f32(1.0) - u))
                       * f32(f32(1.0) - u))
        bend = f32(f32(1.0) + f32(f32(0.35) * u)) if kind == 1 \
            else f32(f32(1.0) - f32(f32(0.15) * u))
        phase = f32(phase + f32(f32(f32(f32(6.2831853) * frequency) * bend)
                                / f32(SAMPLE_RATE)))
        # Peak stays near -7 dBFS including the second harmonic.
        value = f32(f32(f32(12000.0) * envelope)
                    * f32(sinf(phase) + f32(f32(0.18) * sinf(f32(phase * f32(2.0))))))
        out.append(int(value))          # C truncates toward zero on the cast
    return out


def wave():
    return [int(f32(f32(WAVE_PEAK)
                    * sinf(f32(f32(f32(6.2831853) * f32(i)) / f32(WAVE_POINTS)))))
            for i in range(WAVE_POINTS)]


def emit(name, values, ctype='int16_t'):
    text = f'static const {ctype} {name}[] = {{\n'
    text += ',\n'.join(','.join(str(v) for v in values[i:i + 16])
                       for i in range(0, len(values), 16))
    return text + '\n};\n'


def generate(out):
    out.mkdir(parents=True, exist_ok=True)
    flat, offsets = [], []
    for kind in range(len(SFX_FRAMES)):
        offsets.append(len(flat))
        flat += click(kind)
    text = ('// Generated by tools/make_sfx.py. Do not edit.\n'
            '#pragma once\n#include <stdint.h>\n'
            f'enum {{ SFX_KINDS={len(SFX_FRAMES)}, SFX_SAMPLES={len(flat)},'
            f' WAVE_POINTS={WAVE_POINTS} }};\n')
    text += emit('sfx_frames', SFX_FRAMES, 'uint16_t')
    text += emit('sfx_offset', offsets, 'uint16_t')
    text += emit('sfx_pcm', flat)
    text += emit('wave', wave())
    (out / 'sfx_tables.h').write_text(text, encoding='utf-8')


if __name__ == '__main__':
    generate(Path(sys.argv[1]))
