// The equivalence check the editor's differential repaint rests on. Host only
// (WSL: the 5x7 face is generated by make_font.py, and gcc is not on the
// Windows side):
//
//   python3 tools/make_font.py /tmp/cegen
//   gcc -std=gnu11 -O2 -g -Wall -Wextra -Werror -fsanitize=address,undefined
//       -I /tmp/cegen -I tools/hostshim -I main/hal -I main/ui -I main/text
//       tools/test_codeedit.c tools/hostshim/hostshim.c main/ui/codeedit.c
//       main/ui/paint.c main/ui/vimcmd.c main/text/jslex.c -o /tmp/test-codeedit
//   /tmp/test-codeedit
//
// code_draw() sends only the strips whose band hashes moved. Nothing on the
// board can check that: board_capture copies the strip before the byte swap and
// MISO is unwired, so a band left out of the damage set is wrong on the glass
// and right in every screenshot. The check has to be here, where board_present
// writes into an array instead of down a one-way bus.
//
// The property, for every frame: take the panel as the incremental repaints
// left it, force a full repaint over a copy of it, and demand the two agree
// pixel for pixel. A band the incremental pass failed to order keeps its stale
// pixels in the first and is corrected in the second, so the memcmp fails
// exactly when the bookkeeping is wrong -- which is the only bug this design
// can have.
#include "codeedit.h"
#include "keymap.h"
#include "board.h"
#include "jpfont.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// hostshim.c's panel and the strip counter, which is the cost being bought.
extern uint16_t  host_panel[LCD_W*LCD_H];
extern uint16_t *host_target;
extern unsigned  host_strips_sent, host_rows_sent;
void host_ime_present(bool present);
void host_font_ready(jpfont_id_t id, bool on);
void host_console_push(const char *line);

static unsigned failures, frames, strips_incr, strips_full;
static void check(int ok, const char *what) {
    if(!ok) { printf("FAIL %s\n",what); failures++; }
}

static uint16_t full[LCD_W*LCD_H];

// The screen geometry, repeated here on purpose: codeedit.c keeps these
// private, and a test that imported them would follow a mistake in them.
#define T_GUTTER   22
#define T_VIEW_TOP 16
#define T_LINE_H   12
#define T_ROWS     6

static uint16_t px(const uint16_t *fb, int x, int y) { return fb[(size_t)y*LCD_W+x]; }

// The bar drawn at GUTTER-2 when, and only when, the view is scrolled. It is
// the one thing on the panel that reports left_px, which is otherwise private.
static bool scrolled_marker(int row) {
    int y=T_VIEW_TOP+row*T_LINE_H+T_LINE_H/2;
    // GUTTER-1 is the reference, not something further left: the line numbers
    // reach x=18 and would have made every row look scrolled.
    return px(host_panel,T_GUTTER-2,y)!=px(host_panel,T_GUTTER-1,y);
}
static bool any_scrolled(void) {
    for(int r=0;r<T_ROWS;r++) if(scrolled_marker(r)) return true;
    return false;
}

// One frame: draw the way the device does, then prove a full repaint would have
// produced the same panel.
static void frame(const char *what) {
    host_strips_sent=0;
    host_target=host_panel;
    code_draw();
    strips_incr+=host_strips_sent;

    memcpy(full,host_panel,sizeof full);
    host_strips_sent=0;
    host_target=full;
    code_repaint_all();
    code_draw();
    strips_full+=host_strips_sent;
    host_target=host_panel;

    frames++;
    if(memcmp(full,host_panel,sizeof full)) {
        unsigned bad=0; int fx=0, fy=0;
        for(int y=0;y<LCD_H;y++) for(int x=0;x<LCD_W;x++)
            if(px(full,x,y)!=px(host_panel,x,y)) {
                if(!bad) { fx=x; fy=y; }
                bad++;
            }
        printf("FAIL %s: %u px differ, first at (%d,%d) incr=%04x full=%04x\n",
               what,bad,fx,fy,px(host_panel,fx,fy),px(full,fx,fy));
        failures++;
    }
}

// ---- keys, in the encoding main/hal/keymap.c produces ----------------------

static void key_text(const char *utf8, size_t n) {
    keystroke_t k;
    memset(&k,0,sizeof k);
    memcpy(k.text,utf8,n); k.len=(uint8_t)n;
    code_key(&k);
    frame("key");
}
static void ch(char c) { key_text(&c,1); }
static void type(const char *s) { for(const char *p=s;*p;p++) ch(*p); }
// A "\0name" token. The leading NUL is load-bearing, so no strlen here.
static void tok(const char *name) {
    keystroke_t k;
    memset(&k,0,sizeof k);
    size_t n=strlen(name);
    memcpy(k.text+1,name,n); k.len=(uint8_t)(n+1);
    code_key(&k);
    frame(name);
}

// How much of a row is not the background, which is how "the line is on the
// panel" is asked without reaching into the editor's private offsets.
static unsigned row_ink(int row) {
    uint16_t ground=px(host_panel,LCD_W-2,T_VIEW_TOP+row*T_LINE_H);
    unsigned lit=0;
    for(int y=T_VIEW_TOP+row*T_LINE_H;y<T_VIEW_TOP+(row+1)*T_LINE_H;y++)
        for(int x=T_GUTTER;x<LCD_W;x++)
            if(px(host_panel,x,y)!=ground) lit++;
    return lit;
}

int main(void) {
    host_ime_present(true);

    // ---- the template, untouched ------------------------------------------
    code_open();
    frame("open");
    check(!any_scrolled(),"a fresh open is not scrolled");

    // ---- vertical motion --------------------------------------------------
    // Every j walks the window down a line; the row bands are what change and
    // the footer is what does not.
    for(int i=0;i<14;i++) ch('j');
    for(int i=0;i<14;i++) ch('k');

    // ---- horizontal scroll ------------------------------------------------
    // A line far wider than the 218 px text column. The count is deliberate:
    // 300 latin characters is 1,800 px, which is past the 256-byte cap the span
    // table measures from the start of the line.
    ch('C');                       // change to end of line: empties it, insert
    for(int i=0;i<300;i++) ch('x');
    check(any_scrolled(),"typing past the right edge scrolls the view");

    // The text under the caret has to be on the panel, not off the end of the
    // spans. A blank row is the failure this catches: the caret is drawn from
    // the document and would be visible even when the line around it is not.
    {
        int row=-1;
        for(int r=0;r<T_ROWS;r++) if(scrolled_marker(r)) { row=r; break; }
        check(row>=0,"a scrolled row exists");
        unsigned lit=row>=0?row_ink(row):0;
        check(lit>200,"the scrolled row shows its text, not just the caret");
        if(lit<=200) printf("     (only %u lit pixels in the scrolled row)\n",lit);
    }

    tok("esc");
    ch('0');                       // back to the first column
    check(!any_scrolled(),"returning to column 0 unscrolls every row");
    check(row_ink(0)>200 || row_ink(1)>200,"...and the head of the line is drawn");
    ch('$');
    ch('0');

    // ---- multi-byte glyphs ------------------------------------------------
    // The shim's face draws latin at 6 px and everything above U+007F at 12, so
    // a column is neither a byte nor a character. A scroll that counted either
    // would put the caret in the wrong place, and the full repaint would
    // disagree with it.
    ch('o');
    for(int i=0;i<60;i++) key_text("\xe3\x81\x82",3);   // U+3042
    for(int i=0;i<20;i++) type("ab");
    tok("esc");
    ch('0');
    check(!any_scrolled(),"a wide-glyph line unscrolls to column 0 too");
    ch('$');
    check(any_scrolled(),"...and scrolls when the caret is at its end");

    // ---- the IME over a scrolled line -------------------------------------
    ch('i');
    frame("insert over a scrolled line");

    // ---- modes, the footer, and the command line --------------------------
    tok("esc");
    ch(':'); type("w");
    tok("esc");
    ch('d');                       // an operator waiting for its motion
    ch('d');
    ch('u');                       // and undone
    ch('G');
    ch('g'); ch('g');

    // ---- an empty document ------------------------------------------------
    { keystroke_t k; memset(&k,0,sizeof k); k.text[0]=0x0e; k.len=1;
      code_key(&k); frame("C-n"); }
    check(!any_scrolled(),"an emptied document is not scrolled");
    type("hello");
    tok("del"); tok("del");

    // ---- the face arriving late -------------------------------------------
    // jpfont maps its faces out of a partition, so a first repaint can happen
    // before either is ready. draw_row then takes its other branch entirely --
    // paint_ascii through a 32-byte staging buffer at a fixed 6 px -- and
    // hband_env is what makes the frame after the face lands a damaged one.
    // Without that this is precisely a band whose pixels change while its hash
    // does not.
    host_font_ready(JPFONT_TEXT,false);
    frame("the text face went away");
    ch('$');
    ch('0');
    for(int i=0;i<40;i++) ch('l');
    host_font_ready(JPFONT_SMALL,false);
    frame("and the small one");
    host_font_ready(JPFONT_TEXT,true);
    host_font_ready(JPFONT_SMALL,true);
    frame("both faces back");

    // ---- the console and an error line ------------------------------------
    host_console_push("hello from the guest");
    code_returned(NULL);
    frame("returned");
    code_returned("TypeError: t is not a function");
    frame("returned with an error");

    // ---- what the differential repaint actually saves ----------------------
    printf("%u frames, %u strips incremental vs %u full (%.1f%%)\n",
           frames,strips_incr,strips_full,100.0*strips_incr/(double)strips_full);

    code_close();
    if(failures) { printf("%u FAILURES\n",failures); return 1; }
    printf("codeedit: ok\n");
    return 0;
}
